name: Java CI

on:
  push:
    branches: [ main ]
    paths:
      - 'java/**'
      - '.github/workflows/java-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'java/**'
      - '.github/workflows/java-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.KOROMAN_TOKEN }}
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'gradle'
    - name: Run tests
      run: |
        cd java
        ./gradlew test 