name: JavaScript CI

on:
  push:
    branches: [ main ]
    paths:
      - 'js/**'
      - '.github/workflows/js-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'js/**'
      - '.github/workflows/js-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.KOROMAN_TOKEN }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: |
        cd js
        npm ci
    - name: Run tests
      run: |
        cd js
        npm test 